version: 2.1

orbs:
  vro: kohirens/version-release@dev:alpha

parameters:
  ssh_finger:
    description: SSH fingerprint.
    type: string
    default: "8b:ca:bf:49:cc:d6:87:8c:0f:f8:de:63:6f:4c:92:ac"
  triggered_by_bot:
    default: false
    description: Trigger publishing a release tag workflow.
    type: boolean

filter-semantic-tag: &filter-semantic-tag
  tags:
    only: /^v?\d+\.\d+\.\d+$/
  branches:
    ignore: /.*/

jobs:
  co:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}
      - run:
          name: Install Dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: .
          paths: [ . ]

  run-test:
    docker:
      - image: circleci/golang:1.17
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
            keys:
                - go-mod-v1-{{ checksum "go.mod" }}
      - run:
          name: "Unit test"
          command: |
            go test -v

  publish-image:
    docker:
      - image: circleci/golang:1.17
#      - image: kohirens/circle-go:1.17
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: "Build and Publish Docker Release Image"
          command: |
            echo "Publishing tag '<< pipeline.git.tag >>'"
            export BUILD_VER="0.0.0-dev"
            #export BUILD_VER="<< pipeline.git.tag >>"
            if [ -z "${BUILD_VER}" ]; then
              echo "cannot publish a Docker image, release-tag is empty"
              exit 1
            fi
            export BUILD_IMG="kohirens/tmpltoapp:${BUILD_VER}"
            docker build -t "${BUILD_IMG}" --rm -f .docker/Dockerfile --progress plain .
            #docker push "${BUILD_IMG}"
            docker rm "${BUILD_IMG}"

workflows:
  quality-control:
    jobs:
      - co:
          filters: { branches: { ignore: main } }
      - run-test:
          requires: [ co ]
      - publish-image:
          context: orb-publishing
          requires: [ co ]

  publish-changelog:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [webhook, << pipeline.trigger_source >>]
    jobs:
        - vro/publish-changelog:
            context: orb-publishing
            ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-release-tag:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - << pipeline.parameters.triggered_by_bot >>
    jobs:
      - vro/tag-and-release:
          context: orb-publishing

  on-tag-release:
    jobs:
      - publish-image:
          context: orb-publishing
          filters:
            <<: *filter-semantic-tag
