version: '3.8'

services:
    # docker run -it --entrypoint sh --rm -v  "${PWS}/:/go/src/github.com/kohirens/go-gitter/" --name gitter go_gitter_app
    app:
        build:
            dockerfile: 'docker/Dockerfile'
            context: '..'
            target: 'dev'
        cap_add:
            - 'SYS_PTRACE'
            - 'SYSLOG'
        tty: true
        security_opt:
            - 'seccomp:unconfined'
        volumes:
           - '../:/home/gitter/src/github.com/kohirens/go-gitter'
           - 'vscode_ext:/home/gitter/.vscode-server'
           - 'vscode_i_ext:/home/gitter/.vscode-server-insiders/extensions'
           - '${HOME}:/home/gitter/.ssh/known_hosts'

volumes:
    vscode_ext: null
    vscode_i_ext: null
