version: '3.8'

services:
    node:
        build:
            args:
                USER_NAME: '${USER_NAME}'
                REPO: '${REPO}'
            dockerfile: '.docker/Dockerfile'
            context: '..'
            target: '${BTARGET:-dev}'
        cap_add:
            - 'SYS_PTRACE'
            - 'SYSLOG'
        security_opt:
            - 'seccomp:unconfined'
        volumes:
            - '../:/home/${USER_NAME}/src/${REPO}'
            - '~/.ssh/known_hosts:/home/${USER_NAME}/.ssh/known_hosts'
            # - 'vscode:/home/${USER_NAME}/.vscode-server'

# volumes:
    # vscode: null
